In [1]:
from saem import CSEMData, CSEMSurvey
import matplotlib.pyplot as plt
import numpy as np

In [2]:
tx1 = CSEMData("Tx1_Data.npz")
# tx1.filter(minRxDist=150)
tx1.f

array([  13.89,   18.52,   23.15,   32.  ,   45.25,   64.  ,   90.51,
        128.  ,  181.02,  256.  ,  362.04,  512.  ,  724.08, 1024.  ])

In [3]:
tx2 = CSEMData("TX2_Data.npz")
# tx2.filter(minRxDist=150)
tx2.f

array([  13.89,   18.52,   23.15,   32.  ,   45.25,   64.  ,   90.51,
        128.  ,  181.02,  256.  ,  362.04,  512.  ,  724.08, 1024.  ])

In [4]:
tx3 = CSEMData("TX3_Data.npz")
# tx3.filter(minRxDist=150)
tx3.f

array([  13.89,   18.52,   23.15,   32.  ,   45.25,   64.  ,   90.51,
        128.  ,  181.02,  256.  ,  362.04,  512.  ,  724.08, 1024.  ])

In [4]:
survey = CSEMSurvey()
survey.addPatch(tx1)
survey.addPatch(tx2)
survey.addPatch(tx3)

In [5]:
survey.saveData('Data_Tx1Tx2Tx3')

In [ ]:
from saem import tools

TX1=tools.readCoordsFromKML("TX1_new.kml")
TX2=tools.readCoordsFromKML("TX2_new.kml")
TX3=tools.readCoordsFromKML("TX3_new.kml")
PO=tools.readCoordsFromKML(xmlfile= "Powerlines.kml", proj='utm')
PL=tools.readCoordsFromKML(xmlfile= "Rail.kml", proj='utm')

ax = survey.showPositions(background="MAP")

ax.plot(TX1[0, :], TX1[1, :], '-', markersize=0.5, label="Tx1", color = 'b')
ax.plot(TX2[0, :], TX2[1, :], '-', markersize=0.5, label="Tx2", color = "orange")
ax.plot(TX3[0, :], TX3[1, :], '-', markersize=0.5, label="Tx3", color = 'g')
ax.plot(PO[0, :], PO[1, :], "r", label="Power lines" )
ax.plot(PL[0, :], PL[1, :], "k", label="Railway" )

plt.xlabel("Easting (m) UTM33N")
plt.ylabel("Northing (m) UTM33N")
plt.legend()
plt.legend(fontsize=8.0)
plt.show()